name: Auto Post Generator
on:
  schedule:
    - cron: '0 0 * * *' # كايخدم كل يوم مع 12 دالليل
  workflow_dispatch: # تقدر تخدمو بيدك وقتما بغيتي
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install groq
      - name: Run Generator
        run: python generator.py
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add new daily SEO article" || exit 0
          git push
